---@class PlayerModule
---@field init fun()
---@field get_player fun(color: string): Player
---@field set_last_piece fun(piece: Piece)
---@field set_en_passant fun(color: string, bool: boolean)
---@field get_dead_pawn_en_passant fun(piece: Piece, square: Square, board: Square[][]): Piece
---@field can_perform_en_passant fun(color: string): boolean
---@field can_promote fun(piece: Piece, square: Square): boolean
---@field get_king fun(color: string, pieces: Piece[]): Piece
---@field get_opponent_king fun(color: string, pieces: Piece[]): Piece
---@field inspect_check fun(king: Piece, pieces: Piece[], board: Square[][]): boolean
---@field can_perform_castling fun(king: Piece, square: Square, board: Square[][]): boolean, CastlingMovement

---@class Player
---@field color string
---@field check boolean
---@field hasMoved boolean
---@field enPassantVulnerable boolean

---@class CastlingMovement
---@field tower Piece
---@field newPos Square
---@field lastPos Square
---@field intermediate Square
